trigger: none

variables:
- group: DXP-variables

pool:
  name: Azure Pipelines
  vmImage: 'windows-latest'

steps:

- checkout: none  # Don't sync sources

- task: DxpDeployTo@1
  inputs:
    ClientKey: '$(ClientKey)'
    ClientSecret: '$(ClientSecret)'
    ProjectId: '$(DXP.ProjectId)'
    SourceEnvironment: 'Production'
    TargetEnvironment: 'Preproduction'
    SourceApp: 'cms'
    UseMaintenancePage: false
    IncludeBlob: true
    IncludeDb: true
    Timeout: 1800

- task: DxpCompleteDeploy@1
  inputs:
    ClientKey: '$(ClientKey)'
    ClientSecret: '$(ClientSecret)'
    ProjectId: '$(DXP.ProjectId)'
    TargetEnvironment: 'Preproduction'
    Timeout: 1800